### ISSUE TITLE
Please add a screen shot

### ISSUE THREAD

**Issue by unixorn** [RizkiIqbal02/zsh-theme-custom#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them.

Thanks!

**Comment by RizkiIqbal02** [comment]
Thank you for visiting my repository. I have added some screenshot results related to this theme. Please recheck the repository to review the changes. Thank you.
